# -*- coding: utf-8 -*-
"""DioETL_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Lz0SDDPmC9TZltinUu6SOzQEiBYOakN
"""

api_dio_url = 'https://sdw-2023-prd.up.railway.app'

"""Extract

Extrai a lista de IDs de usuário a partir do CSV. Para cada ID, faça uma requisição GET para obter os dados do usuário correspondente
"""

#TODO Extrai os IDs do arquivo CSV.

import pandas as pd

df = pd.read_csv('SDW2023.csv')
user_ids = df['UserID'].tolist()
print(user_ids)

#TODO Obter os dados de cada ID usando a API da Santander Dev Week 2023
import requests
import json

def get_user(id):
  response = requests.get(f'{api_dio_url}/users/{id}')
  return response.json() if response.status_code == 200 else None

users = [user for id in user_ids if (user := get_user(id)) is not None]
print(json.dumps(users, indent=2))

"""Transform

Utilize a API do OpenAI GPT-4 para gerar uma mensagem de marketing personalizada para cada usuário.
"""

!pip install openai

# Documentação oficial da API OpenAI: https://platform.openai.com/docs/api-reference/introduction
# Informações sobre o Periodo Gratuito:https://help.openai.com/en/articles/4936830

# Para gerar uma API Key:
# 1. Crie uma conta na OpenAI
# 2. Acesse a seção 'API Key'
# 3. Clique em 'Create API key'
# link direto: https://platform.openai.com/account/api-keys

# Substitua o texto TODO por sua API Key da OpenAI, ela será salva como uma variário de ambiente

openai_api_key = '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'

#TODO Implementar a integração com o ChatGPT usando o modelo GPT-4
import openai

openai.api_key = openai_api_key

def generate_ai_news(user):
  completion = openai.ChatCompletion.create(
      model= "gpt-3.5-turbo",
      messages=[
          {"role": "system",
           "content": "Você é um especialista em marketing bancário."
           },
            {"role": "user",
             "content":f"Crie uma mensagem para {user['name']} sobre a importância dos investimentos (máximo de 100 caracteres)"
             }
          ]
      )
  return completion.choices[0].message.content.strip('\"')

for user in users:
  news = generate_ai_news(user)
  print(news)
  user['news'].append({
      "icon":"https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
      "description": news
  })



"""Load

Atualiza a llista de 'news' de cada usuário na API com a nova mensagem gerada
"""

def update_user(user):
  response = requests.put(f"{api_dio_url}/users/{user['id']}", json=users)
  return True if response.status_code == 200 else False

for user in users:
  succes = update_user(user)
  print(f"User {user['name']} updated? {succes}!")

